// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: requesterID, boardID, listID, cardID, _a4
func (_m *Usecase) Create(requesterID primitive.ObjectID, boardID primitive.ObjectID, listID primitive.ObjectID, cardID primitive.ObjectID, _a4 string) error {
	ret := _m.Called(requesterID, boardID, listID, cardID, _a4)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, primitive.ObjectID, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r0 = rf(requesterID, boardID, listID, cardID, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: requesterID, boardID, listID, cardID, commentID, _a5
func (_m *Usecase) Update(requesterID primitive.ObjectID, boardID primitive.ObjectID, listID primitive.ObjectID, cardID primitive.ObjectID, commentID primitive.ObjectID, _a5 string) error {
	ret := _m.Called(requesterID, boardID, listID, cardID, commentID, _a5)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, primitive.ObjectID, primitive.ObjectID, primitive.ObjectID, primitive.ObjectID, string) error); ok {
		r0 = rf(requesterID, boardID, listID, cardID, commentID, _a5)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
