// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/jordyf15/thullo-api/models"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *Repository) Create(_a0 *models.List) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.List) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBoardLists provides a mock function with given fields: boardID
func (_m *Repository) GetBoardLists(boardID primitive.ObjectID) ([]*models.List, error) {
	ret := _m.Called(boardID)

	var r0 []*models.List
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) []*models.List); ok {
		r0 = rf(boardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.List)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(boardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListByID provides a mock function with given fields: listID
func (_m *Repository) GetListByID(listID primitive.ObjectID) (*models.List, error) {
	ret := _m.Called(listID)

	var r0 *models.List
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) *models.List); ok {
		r0 = rf(listID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.List)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(listID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateList provides a mock function with given fields: listID, _a1
func (_m *Repository) UpdateList(listID primitive.ObjectID, _a1 *models.List) error {
	ret := _m.Called(listID, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, *models.List) error); ok {
		r0 = rf(listID, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
