// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: boardID, title
func (_m *Usecase) Create(boardID primitive.ObjectID, title string) error {
	ret := _m.Called(boardID, title)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string) error); ok {
		r0 = rf(boardID, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePosition provides a mock function with given fields: boardID, listID, newPosition
func (_m *Usecase) UpdatePosition(boardID primitive.ObjectID, listID primitive.ObjectID, newPosition int) error {
	ret := _m.Called(boardID, listID, newPosition)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, primitive.ObjectID, int) error); ok {
		r0 = rf(boardID, listID, newPosition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTitle provides a mock function with given fields: listID, title
func (_m *Usecase) UpdateTitle(listID primitive.ObjectID, title string) error {
	ret := _m.Called(listID, title)

	var r0 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string) error); ok {
		r0 = rf(listID, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
