// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/jordyf15/thullo-api/models"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: boardMember
func (_m *Repository) Create(boardMember *models.BoardMember) error {
	ret := _m.Called(boardMember)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.BoardMember) error); ok {
		r0 = rf(boardMember)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBoardMembers provides a mock function with given fields: boardID
func (_m *Repository) GetBoardMembers(boardID primitive.ObjectID) ([]*models.BoardMember, error) {
	ret := _m.Called(boardID)

	var r0 []*models.BoardMember
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) []*models.BoardMember); ok {
		r0 = rf(boardID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.BoardMember)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(boardID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
