// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetImagesForID provides a mock function with given fields: photoID, focalPointY
func (_m *Repository) GetImagesForID(photoID string, focalPointY float64) ([]*os.File, error) {
	ret := _m.Called(photoID, focalPointY)

	var r0 []*os.File
	if rf, ok := ret.Get(0).(func(string, float64) []*os.File); ok {
		r0 = rf(photoID, focalPointY)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*os.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(photoID, focalPointY)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
